// <auto-generated />
using KutuphaneAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneAPI.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20260226232548_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("KutuphaneAPI.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YayinYili")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YazarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YazarId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Yazar");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Kitap", b =>
                {
                    b.HasOne("KutuphaneAPI.Models.Yazar", "YazarBilgisi")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YazarBilgisi");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Yazar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
